// GENERATED by scripts/extract-reference-assets.py — do not edit by hand.
// Every sprite is cut straight out of reference_design.png, and `x`/`y` are
// its position on that 1586x992 canvas, so the page can put it back exactly.

export type Sprite = { name: string; x: number; y: number; w: number; h: number; delay: number };

export const SCATTERED: Sprite[] = [
  { name: "tomato", x: 99, y: 113, w: 125, h: 70, delay: 0 },
  { name: "broccoli", x: 357, y: 177, w: 117, h: 89, delay: 0.5 },
  { name: "eggplant", x: 112, y: 388, w: 96, h: 82, delay: 1.1 },
  { name: "blueberries", x: 145, y: 605, w: 87, h: 61, delay: 1.6 },
  { name: "lemon", x: 186, y: 800, w: 111, h: 76, delay: 0.3 },
  { name: "carrot", x: 1177, y: 97, w: 93, h: 96, delay: 0.8 },
  { name: "banana", x: 1396, y: 255, w: 94, h: 67, delay: 1.4 },
  { name: "apple", x: 1329, y: 406, w: 98, h: 70, delay: 0.2 },
  { name: "avocado", x: 1412, y: 629, w: 106, h: 71, delay: 1.9 },
  { name: "radish", x: 1226, y: 709, w: 72, h: 77, delay: 1.0 },
  { name: "dot-a", x: 1526, y: 528, w: 19, h: 18, delay: 1.5 },
  { name: "dot-b", x: 339, y: 923, w: 19, h: 21, delay: 1.87 },
  { name: "drop-a", x: 216, y: 287, w: 20, h: 23, delay: 0.04 },
  { name: "drop-b", x: 1447, y: 805, w: 18, h: 22, delay: 0.41 },
  { name: "heart-a", x: 572, y: 80, w: 24, h: 22, delay: 0.78 },
  { name: "heart-b", x: 1054, y: 180, w: 20, h: 22, delay: 1.15 },
  { name: "heart-c", x: 294, y: 439, w: 20, h: 19, delay: 1.52 },
  { name: "heart-d", x: 1178, y: 536, w: 28, h: 27, delay: 1.89 },
  { name: "heart-e", x: 353, y: 666, w: 25, h: 25, delay: 0.06 },
  { name: "leaf-a", x: 1121, y: 22, w: 34, h: 34, delay: 0.43 },
  { name: "leaf-b", x: 1407, y: 161, w: 16, h: 17, delay: 0.8 },
  { name: "leaf-c", x: 1202, y: 308, w: 34, h: 36, delay: 1.17 },
  { name: "leaf-d", x: 1048, y: 589, w: 24, h: 32, delay: 1.54 },
  { name: "leaf-e", x: 1332, y: 602, w: 16, h: 15, delay: 1.91 },
  { name: "leaf-f", x: 150, y: 763, w: 15, h: 15, delay: 0.08 },
  { name: "rays", x: 1172, y: 827, w: 33, h: 63, delay: 0.45 },
  { name: "squiggle", x: 301, y: 45, w: 62, h: 34, delay: 0.82 },
  { name: "swoosh", x: 1361, y: 864, w: 74, h: 38, delay: 1.19 },
  { name: "swoosh-left", x: 0, y: 488, w: 101, h: 94, delay: 1.56 },
];

export const POT = { name: "pot", x: 646, y: 67, w: 296, h: 192 };
export const BURST_LEFT = { name: "burst-left", x: 636, y: 406, w: 32, h: 62 };
export const BURST_RIGHT = { name: "burst-right", x: 922, y: 406, w: 30, h: 63 };
